- name: Databrick Notebook Run
  uses: Herman-Wu/databrick-notebook-run-action@released

name: Run Databicks Notebooks GitHub Action Demo 
on: 
  push:
    branches: 
      - main 
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Runs Notebook01a
      uses: Herman-Wu/databrick-notebook-run-action@master
      with:
        databrick-server-uri: 'https://adb-8655177164203606.6.azuredatabricks.net/'
        databrick-token: 'dapi0343f14d87977c15a4321ceb4dd73045'
        databrick-cluster-id: '0111-081832-pubs9hai'
        databrick-local-path: '/github/workspace/<notebook files localtion >'
        databrick-workspace-path: '< workspace path for notebook files >'
        databrick-outfile-path: ' < run task results output folder >'